---
meta:
  name:    carousel
  release: Carousel
  target:  pipes/cloudfoundry-community
  url:     https://pipes.scalecf.net

  initial_version: 0.8.1

  git:
    email: ci@cloudfoundry-community.com
    name:  Cloudfoundry Community CI Bot

  aws:
    access_key: ((aws.access_key_id))
    secret_key: ((aws.secret_access_key))

  github:
    owner:  cloudfoundry-community
    repo:   carousel
    branch: develop
    main-branch: main
    private_key:  ((github.private_key))
    access_token: ((github.access_token))

  slack:
    webhook: ((slack.webhook))
    channel: '#carousel'
